/**
 * AUTO-GENERATED by scripts/generate-data-index.ts — do not edit by hand.
 * Regenerate with: npm run generate:data-index
 *
 * SERVER-SIDE ONLY: bundles the full evaluation dataset. Import via
 * lib/data.ts from server components only — never from 'use client' code.
 * Client list/compare views use lib/data-summaries.ts instead.
 *
 * 196 entities: 68 models, 67 agents, 61 MCP servers.
 */

import type { TrustVectorEntity } from '@/framework/schema/types';

import models_claudeFable5 from '@/data/models/claude-fable-5.json';
import models_claudeHaiku45 from '@/data/models/claude-haiku-4-5.json';
import models_claudeOpus41 from '@/data/models/claude-opus-4-1.json';
import models_claudeOpus45 from '@/data/models/claude-opus-4-5.json';
import models_claudeOpus46 from '@/data/models/claude-opus-4-6.json';
import models_claudeOpus47 from '@/data/models/claude-opus-4-7.json';
import models_claudeOpus48 from '@/data/models/claude-opus-4-8.json';
import models_claudeOpus4 from '@/data/models/claude-opus-4.json';
import models_claudeSonnet45 from '@/data/models/claude-sonnet-4-5.json';
import models_claudeSonnet46 from '@/data/models/claude-sonnet-4-6.json';
import models_claudeSonnet4 from '@/data/models/claude-sonnet-4.json';
import models_claudeSonnet5 from '@/data/models/claude-sonnet-5.json';
import models_commandAPlus from '@/data/models/command-a-plus.json';
import models_deepseekR1 from '@/data/models/deepseek-r1.json';
import models_deepseekV30324 from '@/data/models/deepseek-v3-0324.json';
import models_deepseekV32 from '@/data/models/deepseek-v3-2.json';
import models_deepseekV4 from '@/data/models/deepseek-v4.json';
import models_gemini20Flash from '@/data/models/gemini-2-0-flash.json';
import models_gemini25Pro from '@/data/models/gemini-2-5-pro.json';
import models_gemini31Pro from '@/data/models/gemini-3-1-pro.json';
import models_gemini35Flash from '@/data/models/gemini-3-5-flash.json';
import models_gemini3Flash from '@/data/models/gemini-3-flash.json';
import models_gemini3Pro from '@/data/models/gemini-3-pro.json';
import models_gemma327b from '@/data/models/gemma-3-27b.json';
import models_gemma4 from '@/data/models/gemma-4.json';
import models_glm52 from '@/data/models/glm-5-2.json';
import models_glm5 from '@/data/models/glm-5.json';
import models_gpt41Mini from '@/data/models/gpt-4-1-mini.json';
import models_gpt41Nano from '@/data/models/gpt-4-1-nano.json';
import models_gpt41 from '@/data/models/gpt-4-1.json';
import models_gpt4oMini from '@/data/models/gpt-4o-mini.json';
import models_gpt4o from '@/data/models/gpt-4o.json';
import models_gpt51 from '@/data/models/gpt-5-1.json';
import models_gpt52Codex from '@/data/models/gpt-5-2-codex.json';
import models_gpt52 from '@/data/models/gpt-5-2.json';
import models_gpt53Codex from '@/data/models/gpt-5-3-codex.json';
import models_gpt54 from '@/data/models/gpt-5-4.json';
import models_gpt55 from '@/data/models/gpt-5-5.json';
import models_gpt56 from '@/data/models/gpt-5-6.json';
import models_gpt5 from '@/data/models/gpt-5.json';
import models_gptOss120b from '@/data/models/gpt-oss-120b.json';
import models_gptOss20b from '@/data/models/gpt-oss-20b.json';
import models_grok3Beta from '@/data/models/grok-3-beta.json';
import models_grok41 from '@/data/models/grok-4-1.json';
import models_grok43 from '@/data/models/grok-4-3.json';
import models_grok45 from '@/data/models/grok-4-5.json';
import models_kimiK26 from '@/data/models/kimi-k2-6.json';
import models_kimiK27Code from '@/data/models/kimi-k2-7-code.json';
import models_llama31405b from '@/data/models/llama-3-1-405b.json';
import models_llama3370b from '@/data/models/llama-3-3-70b.json';
import models_llama4Behemoth from '@/data/models/llama-4-behemoth.json';
import models_llama4Maverick from '@/data/models/llama-4-maverick.json';
import models_llama4Scout from '@/data/models/llama-4-scout.json';
import models_minimaxM2 from '@/data/models/minimax-m2.json';
import models_minimaxM3 from '@/data/models/minimax-m3.json';
import models_mistralLarge3 from '@/data/models/mistral-large-3.json';
import models_nemotron3Ultra from '@/data/models/nemotron-3-ultra.json';
import models_nemotronUltra253b from '@/data/models/nemotron-ultra-253b.json';
import models_nova2Lite from '@/data/models/nova-2-lite.json';
import models_novaPro from '@/data/models/nova-pro.json';
import models_openaiO1Mini from '@/data/models/openai-o1-mini.json';
import models_openaiO1 from '@/data/models/openai-o1.json';
import models_openaiO3Mini from '@/data/models/openai-o3-mini.json';
import models_openaiO3 from '@/data/models/openai-o3.json';
import models_openaiO4Mini from '@/data/models/openai-o4-mini.json';
import models_qwen25Vl32b from '@/data/models/qwen2-5-vl-32b.json';
import models_qwen35 from '@/data/models/qwen3-5.json';
import models_qwen36 from '@/data/models/qwen3-6.json';
import agents_activepieces from '@/data/agents/activepieces.json';
import agents_adala from '@/data/agents/adala.json';
import agents_agentgpt from '@/data/agents/agentgpt.json';
import agents_amazonBedrockAgents from '@/data/agents/amazon-bedrock-agents.json';
import agents_amazonKiro from '@/data/agents/amazon-kiro.json';
import agents_amazonLex from '@/data/agents/amazon-lex.json';
import agents_autogen from '@/data/agents/autogen.json';
import agents_autogpt from '@/data/agents/autogpt.json';
import agents_azureBotService from '@/data/agents/azure-bot-service.json';
import agents_babyagi from '@/data/agents/babyagi.json';
import agents_bytedanceTrae from '@/data/agents/bytedance-trae.json';
import agents_chatgptAgent from '@/data/agents/chatgpt-agent.json';
import agents_claudeAgentSdk from '@/data/agents/claude-agent-sdk.json';
import agents_claudeCode from '@/data/agents/claude-code.json';
import agents_claudeCowork from '@/data/agents/claude-cowork.json';
import agents_cline from '@/data/agents/cline.json';
import agents_crewai from '@/data/agents/crewai.json';
import agents_cursorAgent from '@/data/agents/cursor-agent.json';
import agents_devin from '@/data/agents/devin.json';
import agents_dify from '@/data/agents/dify.json';
import agents_e2bAgents from '@/data/agents/e2b-agents.json';
import agents_factoryDroids from '@/data/agents/factory-droids.json';
import agents_flowise from '@/data/agents/flowise.json';
import agents_geminiCli from '@/data/agents/gemini-cli.json';
import agents_githubCopilotCodingAgent from '@/data/agents/github-copilot-coding-agent.json';
import agents_gleanAi from '@/data/agents/glean-ai.json';
import agents_googleAdk from '@/data/agents/google-adk.json';
import agents_googleAgentBuilder from '@/data/agents/google-agent-builder.json';
import agents_googleAntigravity from '@/data/agents/google-antigravity.json';
import agents_googleDialogflow from '@/data/agents/google-dialogflow.json';
import agents_googleJules from '@/data/agents/google-jules.json';
import agents_goose from '@/data/agents/goose.json';
import agents_haystack from '@/data/agents/haystack.json';
import agents_ibmWatsonAssistant from '@/data/agents/ibm-watson-assistant.json';
import agents_jetbrainsJunie from '@/data/agents/jetbrains-junie.json';
import agents_koreAi from '@/data/agents/kore-ai.json';
import agents_langflow from '@/data/agents/langflow.json';
import agents_langgraphAgent from '@/data/agents/langgraph-agent.json';
import agents_llamaindexAgent from '@/data/agents/llamaindex-agent.json';
import agents_lovable from '@/data/agents/lovable.json';
import agents_makeAi from '@/data/agents/make-ai.json';
import agents_manus from '@/data/agents/manus.json';
import agents_mastra from '@/data/agents/mastra.json';
import agents_memgpt from '@/data/agents/memgpt.json';
import agents_microsoftAgentFramework from '@/data/agents/microsoft-agent-framework.json';
import agents_microsoftScout from '@/data/agents/microsoft-scout.json';
import agents_n8nAiAgent from '@/data/agents/n8n-ai-agent.json';
import agents_openaiAgentsSdk from '@/data/agents/openai-agents-sdk.json';
import agents_openaiAssistantsApi from '@/data/agents/openai-assistants-api.json';
import agents_openaiCodex from '@/data/agents/openai-codex.json';
import agents_openclaw from '@/data/agents/openclaw.json';
import agents_opencode from '@/data/agents/opencode.json';
import agents_perplexityComet from '@/data/agents/perplexity-comet.json';
import agents_poke from '@/data/agents/poke.json';
import agents_pydanticAi from '@/data/agents/pydantic-ai.json';
import agents_rasa from '@/data/agents/rasa.json';
import agents_relevanceAi from '@/data/agents/relevance-ai.json';
import agents_replitAgent from '@/data/agents/replit-agent.json';
import agents_salesforceEinsteinBots from '@/data/agents/salesforce-einstein-bots.json';
import agents_semanticKernelAgent from '@/data/agents/semantic-kernel-agent.json';
import agents_sierraAi from '@/data/agents/sierra-ai.json';
import agents_smolagents from '@/data/agents/smolagents.json';
import agents_strandsAgents from '@/data/agents/strands-agents.json';
import agents_superagi from '@/data/agents/superagi.json';
import agents_swarm from '@/data/agents/swarm.json';
import agents_warp from '@/data/agents/warp.json';
import agents_zapierAi from '@/data/agents/zapier-ai.json';
import mcps_mcpServerApify from '@/data/mcps/mcp-server-apify.json';
import mcps_mcpServerAsana from '@/data/mcps/mcp-server-asana.json';
import mcps_mcpServerAtlassian from '@/data/mcps/mcp-server-atlassian.json';
import mcps_mcpServerAws from '@/data/mcps/mcp-server-aws.json';
import mcps_mcpServerAzure from '@/data/mcps/mcp-server-azure.json';
import mcps_mcpServerBox from '@/data/mcps/mcp-server-box.json';
import mcps_mcpServerBraveSearch from '@/data/mcps/mcp-server-brave-search.json';
import mcps_mcpServerBrowserbase from '@/data/mcps/mcp-server-browserbase.json';
import mcps_mcpServerCalendar from '@/data/mcps/mcp-server-calendar.json';
import mcps_mcpServerCanva from '@/data/mcps/mcp-server-canva.json';
import mcps_mcpServerChromeDevtools from '@/data/mcps/mcp-server-chrome-devtools.json';
import mcps_mcpServerClickhouse from '@/data/mcps/mcp-server-clickhouse.json';
import mcps_mcpServerCloudflare from '@/data/mcps/mcp-server-cloudflare.json';
import mcps_mcpServerContext7 from '@/data/mcps/mcp-server-context7.json';
import mcps_mcpServerDatabricks from '@/data/mcps/mcp-server-databricks.json';
import mcps_mcpServerDatadog from '@/data/mcps/mcp-server-datadog.json';
import mcps_mcpServerDocker from '@/data/mcps/mcp-server-docker.json';
import mcps_mcpServerElasticsearch from '@/data/mcps/mcp-server-elasticsearch.json';
import mcps_mcpServerEverything from '@/data/mcps/mcp-server-everything.json';
import mcps_mcpServerExa from '@/data/mcps/mcp-server-exa.json';
import mcps_mcpServerFetch from '@/data/mcps/mcp-server-fetch.json';
import mcps_mcpServerFigma from '@/data/mcps/mcp-server-figma.json';
import mcps_mcpServerFilesystem from '@/data/mcps/mcp-server-filesystem.json';
import mcps_mcpServerFirecrawl from '@/data/mcps/mcp-server-firecrawl.json';
import mcps_mcpServerGit from '@/data/mcps/mcp-server-git.json';
import mcps_mcpServerGithub from '@/data/mcps/mcp-server-github.json';
import mcps_mcpServerGitlab from '@/data/mcps/mcp-server-gitlab.json';
import mcps_mcpServerGmail from '@/data/mcps/mcp-server-gmail.json';
import mcps_mcpServerGoogleDrive from '@/data/mcps/mcp-server-google-drive.json';
import mcps_mcpServerGrafana from '@/data/mcps/mcp-server-grafana.json';
import mcps_mcpServerHubspot from '@/data/mcps/mcp-server-hubspot.json';
import mcps_mcpServerHuggingFace from '@/data/mcps/mcp-server-hugging-face.json';
import mcps_mcpServerKubernetes from '@/data/mcps/mcp-server-kubernetes.json';
import mcps_mcpServerLinear from '@/data/mcps/mcp-server-linear.json';
import mcps_mcpServerMemory from '@/data/mcps/mcp-server-memory.json';
import mcps_mcpServerMongodb from '@/data/mcps/mcp-server-mongodb.json';
import mcps_mcpServerNeo4j from '@/data/mcps/mcp-server-neo4j.json';
import mcps_mcpServerNeon from '@/data/mcps/mcp-server-neon.json';
import mcps_mcpServerNotion from '@/data/mcps/mcp-server-notion.json';
import mcps_mcpServerPaypal from '@/data/mcps/mcp-server-paypal.json';
import mcps_mcpServerPerplexity from '@/data/mcps/mcp-server-perplexity.json';
import mcps_mcpServerPlaywright from '@/data/mcps/mcp-server-playwright.json';
import mcps_mcpServerPostgres from '@/data/mcps/mcp-server-postgres.json';
import mcps_mcpServerPuppeteer from '@/data/mcps/mcp-server-puppeteer.json';
import mcps_mcpServerRedis from '@/data/mcps/mcp-server-redis.json';
import mcps_mcpServerS3 from '@/data/mcps/mcp-server-s3.json';
import mcps_mcpServerSalesforce from '@/data/mcps/mcp-server-salesforce.json';
import mcps_mcpServerSentry from '@/data/mcps/mcp-server-sentry.json';
import mcps_mcpServerSequentialThinking from '@/data/mcps/mcp-server-sequential-thinking.json';
import mcps_mcpServerSerena from '@/data/mcps/mcp-server-serena.json';
import mcps_mcpServerShadcn from '@/data/mcps/mcp-server-shadcn.json';
import mcps_mcpServerShopify from '@/data/mcps/mcp-server-shopify.json';
import mcps_mcpServerSlack from '@/data/mcps/mcp-server-slack.json';
import mcps_mcpServerSnowflake from '@/data/mcps/mcp-server-snowflake.json';
import mcps_mcpServerSqlite from '@/data/mcps/mcp-server-sqlite.json';
import mcps_mcpServerStripe from '@/data/mcps/mcp-server-stripe.json';
import mcps_mcpServerSupabase from '@/data/mcps/mcp-server-supabase.json';
import mcps_mcpServerTavily from '@/data/mcps/mcp-server-tavily.json';
import mcps_mcpServerTime from '@/data/mcps/mcp-server-time.json';
import mcps_mcpServerVercel from '@/data/mcps/mcp-server-vercel.json';
import mcps_mcpServerZapier from '@/data/mcps/mcp-server-zapier.json';

export const ALL_ENTITIES: TrustVectorEntity[] = [
  // models (68)
  models_claudeFable5,
  models_claudeHaiku45,
  models_claudeOpus41,
  models_claudeOpus45,
  models_claudeOpus46,
  models_claudeOpus47,
  models_claudeOpus48,
  models_claudeOpus4,
  models_claudeSonnet45,
  models_claudeSonnet46,
  models_claudeSonnet4,
  models_claudeSonnet5,
  models_commandAPlus,
  models_deepseekR1,
  models_deepseekV30324,
  models_deepseekV32,
  models_deepseekV4,
  models_gemini20Flash,
  models_gemini25Pro,
  models_gemini31Pro,
  models_gemini35Flash,
  models_gemini3Flash,
  models_gemini3Pro,
  models_gemma327b,
  models_gemma4,
  models_glm52,
  models_glm5,
  models_gpt41Mini,
  models_gpt41Nano,
  models_gpt41,
  models_gpt4oMini,
  models_gpt4o,
  models_gpt51,
  models_gpt52Codex,
  models_gpt52,
  models_gpt53Codex,
  models_gpt54,
  models_gpt55,
  models_gpt56,
  models_gpt5,
  models_gptOss120b,
  models_gptOss20b,
  models_grok3Beta,
  models_grok41,
  models_grok43,
  models_grok45,
  models_kimiK26,
  models_kimiK27Code,
  models_llama31405b,
  models_llama3370b,
  models_llama4Behemoth,
  models_llama4Maverick,
  models_llama4Scout,
  models_minimaxM2,
  models_minimaxM3,
  models_mistralLarge3,
  models_nemotron3Ultra,
  models_nemotronUltra253b,
  models_nova2Lite,
  models_novaPro,
  models_openaiO1Mini,
  models_openaiO1,
  models_openaiO3Mini,
  models_openaiO3,
  models_openaiO4Mini,
  models_qwen25Vl32b,
  models_qwen35,
  models_qwen36,
  // agents (67)
  agents_activepieces,
  agents_adala,
  agents_agentgpt,
  agents_amazonBedrockAgents,
  agents_amazonKiro,
  agents_amazonLex,
  agents_autogen,
  agents_autogpt,
  agents_azureBotService,
  agents_babyagi,
  agents_bytedanceTrae,
  agents_chatgptAgent,
  agents_claudeAgentSdk,
  agents_claudeCode,
  agents_claudeCowork,
  agents_cline,
  agents_crewai,
  agents_cursorAgent,
  agents_devin,
  agents_dify,
  agents_e2bAgents,
  agents_factoryDroids,
  agents_flowise,
  agents_geminiCli,
  agents_githubCopilotCodingAgent,
  agents_gleanAi,
  agents_googleAdk,
  agents_googleAgentBuilder,
  agents_googleAntigravity,
  agents_googleDialogflow,
  agents_googleJules,
  agents_goose,
  agents_haystack,
  agents_ibmWatsonAssistant,
  agents_jetbrainsJunie,
  agents_koreAi,
  agents_langflow,
  agents_langgraphAgent,
  agents_llamaindexAgent,
  agents_lovable,
  agents_makeAi,
  agents_manus,
  agents_mastra,
  agents_memgpt,
  agents_microsoftAgentFramework,
  agents_microsoftScout,
  agents_n8nAiAgent,
  agents_openaiAgentsSdk,
  agents_openaiAssistantsApi,
  agents_openaiCodex,
  agents_openclaw,
  agents_opencode,
  agents_perplexityComet,
  agents_poke,
  agents_pydanticAi,
  agents_rasa,
  agents_relevanceAi,
  agents_replitAgent,
  agents_salesforceEinsteinBots,
  agents_semanticKernelAgent,
  agents_sierraAi,
  agents_smolagents,
  agents_strandsAgents,
  agents_superagi,
  agents_swarm,
  agents_warp,
  agents_zapierAi,
  // mcps (61)
  mcps_mcpServerApify,
  mcps_mcpServerAsana,
  mcps_mcpServerAtlassian,
  mcps_mcpServerAws,
  mcps_mcpServerAzure,
  mcps_mcpServerBox,
  mcps_mcpServerBraveSearch,
  mcps_mcpServerBrowserbase,
  mcps_mcpServerCalendar,
  mcps_mcpServerCanva,
  mcps_mcpServerChromeDevtools,
  mcps_mcpServerClickhouse,
  mcps_mcpServerCloudflare,
  mcps_mcpServerContext7,
  mcps_mcpServerDatabricks,
  mcps_mcpServerDatadog,
  mcps_mcpServerDocker,
  mcps_mcpServerElasticsearch,
  mcps_mcpServerEverything,
  mcps_mcpServerExa,
  mcps_mcpServerFetch,
  mcps_mcpServerFigma,
  mcps_mcpServerFilesystem,
  mcps_mcpServerFirecrawl,
  mcps_mcpServerGit,
  mcps_mcpServerGithub,
  mcps_mcpServerGitlab,
  mcps_mcpServerGmail,
  mcps_mcpServerGoogleDrive,
  mcps_mcpServerGrafana,
  mcps_mcpServerHubspot,
  mcps_mcpServerHuggingFace,
  mcps_mcpServerKubernetes,
  mcps_mcpServerLinear,
  mcps_mcpServerMemory,
  mcps_mcpServerMongodb,
  mcps_mcpServerNeo4j,
  mcps_mcpServerNeon,
  mcps_mcpServerNotion,
  mcps_mcpServerPaypal,
  mcps_mcpServerPerplexity,
  mcps_mcpServerPlaywright,
  mcps_mcpServerPostgres,
  mcps_mcpServerPuppeteer,
  mcps_mcpServerRedis,
  mcps_mcpServerS3,
  mcps_mcpServerSalesforce,
  mcps_mcpServerSentry,
  mcps_mcpServerSequentialThinking,
  mcps_mcpServerSerena,
  mcps_mcpServerShadcn,
  mcps_mcpServerShopify,
  mcps_mcpServerSlack,
  mcps_mcpServerSnowflake,
  mcps_mcpServerSqlite,
  mcps_mcpServerStripe,
  mcps_mcpServerSupabase,
  mcps_mcpServerTavily,
  mcps_mcpServerTime,
  mcps_mcpServerVercel,
  mcps_mcpServerZapier,
] as TrustVectorEntity[];
